name: Image Builder
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
    paths:
      - .github/workflows/build_image.yml

jobs:
  buildimg:
    name: Build Image
    runs-on: ubuntu-20.04
    container: openwrtorg/imagebuilder:x86-64-21.02.2
    steps:
      - name: Checkout packages
        run: git clone -b packages/x86/64 --single-branch "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}" /tmp/packages

      - name: Env for Openwrt Builder
        env:
          HOME: /home/build
        run: |
          export
          cd $HOME/openwrt
          sed -i "/check_signature/d" repositories.conf
          echo "src custom file:///tmp/packages" >> repositories.conf

      - name: Build Image
        env:
          HOME: /home/build
          PROFILE: generic.x86_64
          PACKAGES: -dnsmasq bash bind-dig ca-bundle ca-certificates coreutils coreutils-nohup curl dnsmasq-full htop ip-full ip6tables-mod-nat ipset iptables iptables-mod-extra iptables-mod-tproxy kmod-tun libcap libcap-bin luci luci-base luci-compat luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn luci-i18n-opkg-zh-cn luci-app-openclash mentohust ruby ruby-yaml
        shell: bash
        run: |
          cd $HOME/openwrt
          makeopts=("PROFILE=${PROFILE%.*}" "PACKAGES=$PACKAGES")
          [[ -d files ]] && makeopts+=("FILES=files/")
          make info
          #sed -i 's/^\s*\(CONFIG_TARGET_ROOTFS_PARTSIZE\)\s*=\s*[^#\n \t]*/\1=256/' .config
          TERM=xterm-256color make image "${makeopts[@]}"
      - name: Upload Image
        env:
          HOME: /home/build
          PROFILE: generic.x86_64
        run: |
          cd $HOME/openwrt/bin/targets/x86/64
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config http.postBuffer 524288000
          git config https.postBuffer 524288000
          git config core.compression -1
          git add .
          git commit -m "$PROFILE$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:image/$PROFILE
